services:
  db:
    image: postgres:15-alpine
    container_name: comidaconsabor_db
    environment:
      POSTGRES_DB: comida_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: comidaconsabor_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=comida_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=adminpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: comidaconsabor_frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data: