# Generated by Django 5.2.13 on 2026-04-10 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('historia', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('region_origen', models.CharField(blank=True, max_length=100, null=True)),
                ('es_km0', models.BooleanField(default=False)),
                ('es_organico', models.BooleanField(default=False)),
                ('estado_moderacion', models.CharField(choices=[('Pendiente', 'Pendiente de Revisión'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20)),
                ('productor', models.ForeignKey(limit_choices_to={'rol': 'Productor'}, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
